-- AlterTable
ALTER TABLE "Profile" ADD COLUMN     "energy" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "energyMax" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "gems" INTEGER NOT NULL DEFAULT 500,
ADD COLUMN     "lastEnergyRegenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
